# Generated by Django 5.1.1 on 2024-10-23 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Carding', 'Carding Machine'), ('Breaker', 'Breaker Machine'), ('Unilap', 'Unilap Machine'), ('Comber', 'Comber Machine'), ('Finisher', 'Finisher Machine'), ('Roving', 'Roving Machine')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('design', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('num_inputs', models.IntegerField()),
                ('num_outputs', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Carding', 'Carding'), ('Breaker', 'Breaker'), ('Unilap', 'Unilap'), ('Comber', 'Comber'), ('Finisher', 'Finisher'), ('Roving', 'Roving')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='rimtex.mill')),
            ],
        ),
        migrations.CreateModel(
            name='MillLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
        migrations.CreateModel(
            name='MillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('layout_data', models.JSONField(blank=True, null=True)),
                ('is_start', models.BooleanField(default=False)),
                ('machine_types', models.ManyToManyField(blank=True, to='rimtex.machinetype')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
        migrations.CreateModel(
            name='MillMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Carding', 'Carding Machine'), ('Breaker', 'Breaker Machine'), ('Unilap', 'Unilap Machine'), ('Comber', 'Comber Machine'), ('Finisher', 'Finisher Machine'), ('Roving', 'Roving Machine')], max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('make_year', models.IntegerField()),
                ('design', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('num_inputs', models.IntegerField()),
                ('num_outputs', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='machine_images/')),
                ('machine_name', models.CharField(max_length=100)),
                ('is_assigned', models.BooleanField(default=False)),
                ('loading_time', models.IntegerField(null=True)),
                ('unloading_time', models.IntegerField(null=True)),
                ('loading_details_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unloading_details_m', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('loading_details_kg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unloading_details_kg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rimtex.millline')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
        migrations.CreateModel(
            name='MillShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(max_length=10)),
                ('shift_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
        migrations.CreateModel(
            name='SetupMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_add', models.BooleanField(default=False)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.machinetype')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rimtex.mill')),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='machine_types',
            field=models.ManyToManyField(blank=True, related_name='mills', through='rimtex.SetupMachine', to='rimtex.machinetype'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('mill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rimtex.mill')),
            ],
        ),
    ]
